using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AvalaraCodingChallenge.TaxCalculator.Infrastructure;
using Microsoft.AspNetCore.Hosting;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Hosting;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.DependencyInjection;

namespace AvalaraCodingChallenge.TaxCalculator.Web
{
    public class Program
    {
        public static void Main(string[] args)
        {
            var host = CreateHostBuilder(args).Build();
            using(var scope = host.Services.CreateScope())
            {
                var ctx = scope.ServiceProvider.GetService<TaxContext>();
                PopulateInMemoryDatabase(ctx);
            }
            host.Run();
        }

        public static IHostBuilder CreateHostBuilder(string[] args) =>
            Host.CreateDefaultBuilder(args)
                .ConfigureWebHostDefaults(webBuilder =>
                {
                    webBuilder.UseStartup<Startup>();
                });

                
        // This would ideally be stored in a permanent location, but for
        //  example purposes, this will do.
        private static void PopulateInMemoryDatabase(TaxContext context)
        {
            var state = new Domain.Tax.State("NC", 1);
            context.States.Add(state);
            
            state.AddCity("Charlotte", 7.25m / 100m);
            state.AddCity("Raleigh", 7.25m / 100m);
            state.AddCity("Greensboro", 6.75m / 100m);
            state.AddCity("Winston Salem", 7m / 100m);
            state.AddCity("Durham", 7.5m / 100m);
            state.AddCity("Fayetteville", 7m / 100m);
            state.AddCity("Cary", 7.25m / 100m);
            state.AddCity("Wilmington", 7m / 100m);
            state.AddCity("Asheville", 7m / 100m);
            state.AddCity("Concord", 7m / 100m);
            state.AddCity("High Point", 6.75m / 100m);
            state.AddCity("Greenville", 7m / 100m);
            state.AddCity("Hickory", 7m / 100m);
            state.AddCity("Monroe", 6.75m / 100m);
            state.AddCity("Burlington", 6.75m / 100m);
            state.AddCity("Lexington", 7m / 100m);
            state.AddCity("Mooresville", 6.75m / 100m);
            state.AddCity("Rocky Mount", 7m / 100m);
            state.AddCity("Goldsboro", 6.75m / 100m);
            state.AddCity("Gastonia", 7m / 100m);
            state.AddCity("Hendersonville", 6.75m / 100m);
            state.AddCity("Wilson", 6.75m / 100m);
            state.AddCity("Fayetteville", 7m / 100m);
            state.AddCity("Huntersville", 7.25m / 100m);
            state.AddCity("Clayton", 6.75m / 100m);
            state.AddCity("Kernersville", 7m / 100m);
            state.AddCity("Wake Forest", 7.25m / 100m);
            state.AddCity("Salisbury", 7m / 100m);
            state.AddCity("Charlotte", 7.25m / 100m);
            state.AddCity("Jacksonville", 7m / 100m);
            state.AddCity("Kannapolis", 7m / 100m);
            state.AddCity("Morganton", 6.75m / 100m);
            state.AddCity("Waxhaw", 6.75m / 100m);
            state.AddCity("Thomasville", 7m / 100m);
            state.AddCity("Lenoir", 6.75m / 100m);
            state.AddCity("Garner", 7.25m / 100m);
            state.AddCity("Matthews", 7.25m / 100m);
            state.AddCity("Jacksonville", 7m / 100m);
            state.AddCity("Fuquay Varina", 7.25m / 100m);
            state.AddCity("New Bern", 6.75m / 100m);
            state.AddCity("Elizabeth City", 7m / 100m);
            state.AddCity("Henderson", 6.75m / 100m);
            state.AddCity("Sanford", 7m / 100m);
            state.AddCity("Reidsville", 7m / 100m);
            state.AddCity("Statesville", 6.75m / 100m);
            state.AddCity("Mount Airy", 7m / 100m);
            state.AddCity("Lincolnton", 7m / 100m);
            state.AddCity("Lumberton", 7m / 100m);
            state.AddCity("Raeford", 6.75m / 100m);
            state.AddCity("Statesville", 6.75m / 100m);
            state.AddCity("Apex", 7.25m / 100m);
            state.AddCity("Hope Mills", 7m / 100m);
            state.AddCity("Chapel Hill", 7.5m / 100m);
            state.AddCity("Indian Trail", 6.75m / 100m);
            state.AddCity("Gastonia", 7m / 100m);
            state.AddCity("Wilmington", 7m / 100m);
            state.AddCity("Asheboro", 7m / 100m);
            state.AddCity("Holly Springs", 7.25m / 100m);
            state.AddCity("Matthews", 6.75m / 100m);
            state.AddCity("Graham", 6.75m / 100m);
            state.AddCity("Clemmons", 7m / 100m);
            state.AddCity("Marion", 6.75m / 100m);
            state.AddCity("Newton", 7m / 100m);
            state.AddCity("Sanford", 7m / 100m);
            state.AddCity("New Bern", 6.75m / 100m);
            state.AddCity("Shelby", 6.75m / 100m);
            state.AddCity("Mebane", 6.75m / 100m);
            state.AddCity("Washington", 6.75m / 100m);
            state.AddCity("Kings Mountain", 6.75m / 100m);
            state.AddCity("Leland", 6.75m / 100m);
            state.AddCity("Cornelius", 7.25m / 100m);
            state.AddCity("Roanoke Rapids", 7m / 100m);
            state.AddCity("Hillsborough", 7.5m / 100m);
            state.AddCity("Albemarle", 7m / 100m);
            state.AddCity("Mocksville", 6.75m / 100m);
            state.AddCity("Chapel Hill", 7.5m / 100m);
            state.AddCity("Franklin", 6.75m / 100m);
            state.AddCity("Oxford", 6.75m / 100m);
            state.AddCity("Chapel Hill", 7m / 100m);
            state.AddCity("Conover", 7m / 100m);
            state.AddCity("Taylorsville", 7m / 100m);
            state.AddCity("Winterville", 7m / 100m);
            state.AddCity("Candler", 7m / 100m);
            state.AddCity("Havelock", 6.75m / 100m);
            state.AddCity("Knightdale", 7.25m / 100m);
            state.AddCity("Durham", 7.5m / 100m);
            state.AddCity("Morrisville", 7.25m / 100m);
            state.AddCity("Eden", 7m / 100m);
            state.AddCity("Laurinburg", 6.75m / 100m);
            state.AddCity("Salisbury", 7m / 100m);
            state.AddCity("Clinton", 7m / 100m);
            state.AddCity("Rockingham", 6.75m / 100m);
            state.AddCity("Dunn", 7m / 100m);
            state.AddCity("Shelby", 6.75m / 100m);
            state.AddCity("Zebulon", 7.25m / 100m);
            state.AddCity("Boone", 6.75m / 100m);
            state.AddCity("Newport", 6.75m / 100m);
            state.AddCity("High Point", 7m / 100m);
            state.AddCity("Weaverville", 7m / 100m);
            state.AddCity("Belmont", 7m / 100m);
            state.AddCity("Smithfield", 6.75m / 100m);
            state.AddCity("Kinston", 6.75m / 100m);
            state.AddCity("Louisburg", 6.75m / 100m);
            state.AddCity("Fort Bragg", 7m / 100m);
            state.AddCity("Mount Holly", 7m / 100m);
            state.AddCity("Tarboro", 7m / 100m);
            state.AddCity("Denver", 7m / 100m);
            state.AddCity("Wendell", 7.25m / 100m);
            state.AddCity("Charlotte", 7.25m / 100m);
            state.AddCity("Granite Falls", 6.75m / 100m);
            state.AddCity("Asheboro", 7m / 100m);
            state.AddCity("Pittsboro", 7m / 100m);
            state.AddCity("North Wilkesboro", 7m / 100m);
            state.AddCity("Waynesville", 7m / 100m);
            state.AddCity("Arden", 7m / 100m);
            state.AddCity("Apex", 7.25m / 100m);
            state.AddCity("Pinehurst", 7m / 100m);
            state.AddCity("Rutherfordton", 7m / 100m);
            state.AddCity("Spring Lake", 7m / 100m);
            state.AddCity("King", 6.75m / 100m);
            state.AddCity("Forest City", 7m / 100m);
            state.AddCity("Hampstead", 6.75m / 100m);
            state.AddCity("Siler City", 7m / 100m);
            state.AddCity("Harrisburg", 7m / 100m);
            state.AddCity("Randleman", 7m / 100m);
            state.AddCity("Whiteville", 6.75m / 100m);
            state.AddCity("Kinston", 6.75m / 100m);
            state.AddCity("Angier", 7m / 100m);
            state.AddCity("Canton", 7m / 100m);
            state.AddCity("Fletcher", 6.75m / 100m);
            state.AddCity("Jamestown", 6.75m / 100m);
            state.AddCity("Southport", 6.75m / 100m);
            state.AddCity("Murphy", 7m / 100m);
            state.AddCity("Nashville", 6.75m / 100m);
            state.AddCity("Dallas", 7m / 100m);
            state.AddCity("Brevard", 6.75m / 100m);
            state.AddCity("Trinity", 7m / 100m);
            state.AddCity("Morehead City", 6.75m / 100m);
            state.AddCity("Youngsville", 6.75m / 100m);
            state.AddCity("Advance", 6.75m / 100m);
            state.AddCity("Cameron", 7m / 100m);
            state.AddCity("Willow Spring", 7.25m / 100m);
            state.AddCity("Stanley", 7m / 100m);
            state.AddCity("Summerfield", 6.75m / 100m);
            state.AddCity("Hubert", 7m / 100m);
            state.AddCity("Selma", 6.75m / 100m);
            state.AddCity("China Grove", 7m / 100m);
            state.AddCity("Carthage", 7m / 100m);
            state.AddCity("Richlands", 7m / 100m);
            state.AddCity("Yadkinville", 6.75m / 100m);
            state.AddCity("Burnsville", 6.75m / 100m);
            state.AddCity("Davidson", 7.25m / 100m);
            state.AddCity("Southern Pines", 7m / 100m);
            state.AddCity("Lillington", 7m / 100m);
            state.AddCity("Williamston", 7m / 100m);
            state.AddCity("Benson", 6.75m / 100m);
            state.AddCity("Roxboro", 6.75m / 100m);
            state.AddCity("Mount Olive", 6.75m / 100m);
            state.AddCity("Carrboro", 7.5m / 100m);
            state.AddCity("Lewisville", 7m / 100m);
            state.AddCity("Cherryville", 7m / 100m);
            state.AddCity("Maiden", 7m / 100m);
            state.AddCity("La Grange", 6.75m / 100m);
            state.AddCity("Bessemer City", 7m / 100m);
            state.AddCity("Franklinton", 6.75m / 100m);
            state.AddCity("Sylva", 7m / 100m);
            state.AddCity("Hudson", 6.75m / 100m);
            state.AddCity("Edenton", 6.75m / 100m);
            state.AddCity("Gibsonville", 6.75m / 100m);
            state.AddCity("Creedmoor", 6.75m / 100m);
            state.AddCity("Pembroke", 7m / 100m);
            state.AddCity("Swansboro", 7m / 100m);
            state.AddCity("Black Mountain", 7m / 100m);
            state.AddCity("Leicester", 7m / 100m);
            state.AddCity("Wilkesboro", 7m / 100m);
            state.AddCity("Pfafftown", 7m / 100m);
            state.AddCity("Hamlet", 6.75m / 100m);
            state.AddCity("Four Oaks", 6.75m / 100m);
            state.AddCity("Beaufort", 6.75m / 100m);
            state.AddCity("Kill Devil Hills", 6.75m / 100m);
            state.AddCity("Pikeville", 6.75m / 100m);
            state.AddCity("Maxton", 7m / 100m);
            state.AddCity("Saint Pauls", 7m / 100m);
            state.AddCity("Hertford", 6.75m / 100m);
            state.AddCity("Madison", 7m / 100m);
            state.AddCity("Browns Summit", 6.75m / 100m);
            state.AddCity("Roxboro", 6.75m / 100m);
            state.AddCity("Rockwell", 7m / 100m);
            state.AddCity("Wadesboro", 7m / 100m);
            state.AddCity("Supply", 6.75m / 100m);
            state.AddCity("Elon", 6.75m / 100m);
            state.AddCity("Aberdeen", 7m / 100m);
            state.AddCity("Marshall", 7m / 100m);
            state.AddCity("Liberty", 7m / 100m);
            state.AddCity("Walnut Cove", 6.75m / 100m);
            state.AddCity("Ahoskie", 7m / 100m);
            state.AddCity("Lumberton", 7m / 100m);
            state.AddCity("Claremont", 7m / 100m);
            state.AddCity("Dudley", 6.75m / 100m);
            state.AddCity("Moyock", 6.75m / 100m);
            state.AddCity("Connellys Springs", 6.75m / 100m);
            state.AddCity("Vale", 7m / 100m);
            state.AddCity("Marshville", 6.75m / 100m);
            state.AddCity("Clyde", 7m / 100m);
            state.AddCity("Red Springs", 7m / 100m);
            state.AddCity("Elkin", 7m / 100m);
            state.AddCity("Rocky Point", 6.75m / 100m);
            state.AddCity("Fairview", 7m / 100m);
            state.AddCity("Swannanoa", 7m / 100m);
            state.AddCity("Troutman", 6.75m / 100m);
            state.AddCity("Burgaw", 6.75m / 100m);
            state.AddCity("Apex", 7m / 100m);
            state.AddCity("Ayden", 7m / 100m);
            state.AddCity("Fairmont", 7m / 100m);
            state.AddCity("Mc Leansville", 6.75m / 100m);
            state.AddCity("Pineville", 7.25m / 100m);
            state.AddCity("Snow Hill", 7m / 100m);
            state.AddCity("West End", 7m / 100m);
            state.AddCity("Elizabethtown", 6.75m / 100m);
            state.AddCity("Denton", 7m / 100m);
            state.AddCity("Wallace", 7m / 100m);
            state.AddCity("Kenly", 6.75m / 100m);
            state.AddCity("Rural Hall", 7m / 100m);
            state.AddCity("Calabash", 6.75m / 100m);
            state.AddCity("Valdese", 6.75m / 100m);
            state.AddCity("Spruce Pine", 6.75m / 100m);
            state.AddCity("Bryson City", 7m / 100m);
            state.AddCity("Elm City", 6.75m / 100m);
            state.AddCity("Farmville", 7m / 100m);
            state.AddCity("Kitty Hawk", 6.75m / 100m);
            state.AddCity("Stoneville", 7m / 100m);
            state.AddCity("Dobson", 7m / 100m);
            state.AddCity("Oak Ridge", 6.75m / 100m);
            state.AddCity("Stokesdale", 7m / 100m);
            state.AddCity("Flat Rock", 6.75m / 100m);
            state.AddCity("Windsor", 7m / 100m);
            state.AddCity("East Bend", 6.75m / 100m);
            state.AddCity("Sneads Ferry", 7m / 100m);
            state.AddCity("West Jefferson", 7m / 100m);
            state.AddCity("Shallotte", 6.75m / 100m);
            state.AddCity("Cherokee", 7m / 100m);
            state.AddCity("Wingate", 6.75m / 100m);
            state.AddCity("Pilot Mountain", 7m / 100m);
            state.AddCity("Castle Hayne", 7m / 100m);
            state.AddCity("Walkertown", 7m / 100m);
            state.AddCity("Hayesville", 7m / 100m);
            state.AddCity("Robbinsville", 7m / 100m);
            state.AddCity("Iron Station", 7m / 100m);
            state.AddCity("Bladenboro", 6.75m / 100m);
            state.AddCity("Norwood", 7m / 100m);
            state.AddCity("Spring Hope", 6.75m / 100m);
            state.AddCity("Princeton", 6.75m / 100m);
            state.AddCity("Enfield", 7m / 100m);
            state.AddCity("Camp Lejeune", 7m / 100m);
            state.AddCity("Chocowinity", 6.75m / 100m);
            state.AddCity("Pleasant Garden", 6.75m / 100m);
            state.AddCity("Nebo", 6.75m / 100m);
            state.AddCity("Whitsett", 6.75m / 100m);
            state.AddCity("Middlesex", 6.75m / 100m);
            state.AddCity("Timberlake", 6.75m / 100m);
            state.AddCity("Newland", 6.75m / 100m);
            state.AddCity("Lawndale", 6.75m / 100m);
            state.AddCity("Plymouth", 6.75m / 100m);
            state.AddCity("Beulaville", 7m / 100m);
            state.AddCity("Troy", 7m / 100m);
            state.AddCity("Old Fort", 6.75m / 100m);
            state.AddCity("Pisgah Forest", 6.75m / 100m);
            state.AddCity("Oak Island", 6.75m / 100m);
            state.AddCity("Grifton", 7m / 100m);
            state.AddCity("Rougemont", 7.5m / 100m);
            state.AddCity("Vanceboro", 6.75m / 100m);
            state.AddCity("Mount Pleasant", 7m / 100m);
            state.AddCity("Tabor City", 6.75m / 100m);
            state.AddCity("Midland", 7m / 100m);
            state.AddCity("Mars Hill", 7m / 100m);
            state.AddCity("Millers Creek", 7m / 100m);
            state.AddCity("Mills River", 6.75m / 100m);
            state.AddCity("Roseboro", 7m / 100m);
            state.AddCity("Ramseur", 7m / 100m);
            state.AddCity("Ellenboro", 7m / 100m);
            state.AddCity("Bailey", 6.75m / 100m);
            state.AddCity("Littleton", 7m / 100m);
            state.AddCity("Waynesville", 7m / 100m);
            state.AddCity("Manteo", 6.75m / 100m);
            state.AddCity("Warrenton", 6.75m / 100m);
            state.AddCity("Ocean Isle Beach", 6.75m / 100m);
            state.AddCity("Rowland", 7m / 100m);
            state.AddCity("Robbins", 7m / 100m);
            state.AddCity("Erwin", 7m / 100m);
            state.AddCity("Sophia", 7m / 100m);
            state.AddCity("Chadbourn", 6.75m / 100m);
            state.AddCity("Sherrills Ford", 7m / 100m);
            state.AddCity("Hamptonville", 6.75m / 100m);
            state.AddCity("Haw River", 6.75m / 100m);
            state.AddCity("New London", 7m / 100m);
            state.AddCity("Warsaw", 7m / 100m);
            state.AddCity("Columbus", 6.75m / 100m);
            state.AddCity("Holly Ridge", 6.75m / 100m);
            state.AddCity("Snow Camp", 6.75m / 100m);
            state.AddCity("Carolina Beach", 7m / 100m);
            state.AddCity("Catawba", 7m / 100m);
            state.AddCity("Pinnacle", 6.75m / 100m);
            state.AddCity("Sparta", 6.75m / 100m);
            state.AddCity("Bolivia", 6.75m / 100m);
            state.AddCity("Parkton", 7m / 100m);
            state.AddCity("Cleveland", 7m / 100m);
            state.AddCity("Broadway", 7m / 100m);
            state.AddCity("Mount Gilead", 7m / 100m);
            state.AddCity("Bakersville", 6.75m / 100m);
            state.AddCity("Tryon", 6.75m / 100m);
            state.AddCity("Coats", 7m / 100m);
            state.AddCity("Rose Hill", 7m / 100m);
            state.AddCity("Banner Elk", 6.75m / 100m);
            state.AddCity("Pink Hill", 7m / 100m);
            state.AddCity("Grimesland", 7m / 100m);
            state.AddCity("Cullowhee", 7m / 100m);
            state.AddCity("Stedman", 7m / 100m);
            state.AddCity("Oakboro", 7m / 100m);
            state.AddCity("Mooresboro", 6.75m / 100m);
            state.AddCity("Locust", 7m / 100m);
            state.AddCity("Midway Park", 7m / 100m);
            state.AddCity("Camp Lejeune", 7m / 100m);
            state.AddCity("Seagrove", 7m / 100m);
            state.AddCity("Hiddenite", 7m / 100m);
            state.AddCity("Jonesville", 6.75m / 100m);
            state.AddCity("Lucama", 6.75m / 100m);
            state.AddCity("Whittier", 7m / 100m);
            state.AddCity("Maysville", 7m / 100m);
            state.AddCity("Whitakers", 6.75m / 100m);
            state.AddCity("Stony Point", 7m / 100m);
            state.AddCity("Linwood", 7m / 100m);
            state.AddCity("Boonville", 6.75m / 100m);
            state.AddCity("Stanfield", 7m / 100m);
            state.AddCity("Harmony", 6.75m / 100m);
            state.AddCity("Camden", 6.75m / 100m);
            state.AddCity("Grover", 6.75m / 100m);
            state.AddCity("Newton Grove", 7m / 100m);
            state.AddCity("Battleboro", 6.75m / 100m);
            state.AddCity("Murfreesboro", 7m / 100m);
            state.AddCity("Vass", 7m / 100m);
            state.AddCity("Bostic", 7m / 100m);
            state.AddCity("Morganton", 6.75m / 100m);
            state.AddCity("Andrews", 7m / 100m);
            state.AddCity("Pinetops", 7m / 100m);
            state.AddCity("Shannon", 7m / 100m);
            state.AddCity("Colfax", 6.75m / 100m);
            state.AddCity("Linden", 7m / 100m);
            state.AddCity("Seven Springs", 6.75m / 100m);
            state.AddCity("Efland", 7.5m / 100m);
            state.AddCity("Laurel Hill", 6.75m / 100m);
            state.AddCity("Tarawa Terrace", 7m / 100m);
            state.AddCity("Winnabow", 6.75m / 100m);
            state.AddCity("Yanceyville", 6.75m / 100m);
            state.AddCity("Jefferson", 7m / 100m);
            state.AddCity("Autryville", 7m / 100m);
            state.AddCity("Sunset Beach", 6.75m / 100m);
            state.AddCity("Robersonville", 7m / 100m);
            state.AddCity("Clarkton", 6.75m / 100m);
            state.AddCity("Fremont", 6.75m / 100m);
            state.AddCity("Biscoe", 7m / 100m);
            state.AddCity("Scotland Neck", 7m / 100m);
            state.AddCity("Willard", 6.75m / 100m);
            state.AddCity("Rolesville", 7.25m / 100m);
            state.AddCity("Franklinville", 7m / 100m);
            state.AddCity("Mayodan", 7m / 100m);
            state.AddCity("Tobaccoville", 7m / 100m);
            state.AddCity("Germanton", 6.75m / 100m);
            state.AddCity("Faison", 7m / 100m);
            state.AddCity("Ellerbe", 6.75m / 100m);
            state.AddCity("Norlina", 6.75m / 100m);
            state.AddCity("Emerald Isle", 6.75m / 100m);
            state.AddCity("Candor", 7m / 100m);
            state.AddCity("Etowah", 6.75m / 100m);
            state.AddCity("Blowing Rock", 6.75m / 100m);
            state.AddCity("Hurdle Mills", 6.75m / 100m);
            state.AddCity("Butner", 6.75m / 100m);
            state.AddCity("Lowell", 7m / 100m);
            state.AddCity("Bahama", 7.5m / 100m);
            state.AddCity("Kittrell", 6.75m / 100m);
            state.AddCity("Mill Spring", 6.75m / 100m);
            state.AddCity("Ruffin", 7m / 100m);
            state.AddCity("Belhaven", 6.75m / 100m);
            state.AddCity("Trenton", 7m / 100m);
            state.AddCity("Hays", 7m / 100m);
            state.AddCity("Moravian Falls", 7m / 100m);
            state.AddCity("Alexander", 7m / 100m);
            state.AddCity("Columbia", 6.75m / 100m);
            state.AddCity("Vilas", 6.75m / 100m);
            state.AddCity("State Road", 7m / 100m);
            state.AddCity("Gates", 6.75m / 100m);
            state.AddCity("Highlands", 6.75m / 100m);
            state.AddCity("Climax", 7m / 100m);
            state.AddCity("Julian", 6.75m / 100m);
            state.AddCity("Bear Creek", 7m / 100m);
            state.AddCity("South Mills", 6.75m / 100m);
            state.AddCity("Kenansville", 7m / 100m);
            state.AddCity("Magnolia", 7m / 100m);
            state.AddCity("Polkton", 7m / 100m);
            state.AddCity("Stantonsburg", 7m / 100m);
            state.AddCity("Roper", 6.75m / 100m);
            state.AddCity("Riegelwood", 6.75m / 100m);
            state.AddCity("Spindale", 7m / 100m);
            state.AddCity("Pelham", 6.75m / 100m);
            state.AddCity("Maggie Valley", 7m / 100m);
            state.AddCity("Atlantic Beach", 6.75m / 100m);
            state.AddCity("Horse Shoe", 6.75m / 100m);
            state.AddCity("Landis", 7m / 100m);
            state.AddCity("East Flat Rock", 6.75m / 100m);
            state.AddCity("Aulander", 7m / 100m);
            state.AddCity("Ash", 6.75m / 100m);
            state.AddCity("Sims", 6.75m / 100m);
            state.AddCity("Lansing", 7m / 100m);
            state.AddCity("Stem", 6.75m / 100m);
            state.AddCity("Clinton", 7m / 100m);
            state.AddCity("Cramerton", 7m / 100m);
            state.AddCity("Bunnlevel", 7m / 100m);
            state.AddCity("Nags Head", 6.75m / 100m);
            state.AddCity("Westfield", 6.75m / 100m);
            state.AddCity("Garland", 7m / 100m);
            state.AddCity("Gaston", 6.75m / 100m);
            state.AddCity("Jamesville", 7m / 100m);
            state.AddCity("Deep Run", 6.75m / 100m);
            state.AddCity("Roaring River", 7m / 100m);
            state.AddCity("Saluda", 6.75m / 100m);
            state.AddCity("Salemburg", 7m / 100m);
            state.AddCity("Crouse", 7m / 100m);
            state.AddCity("Belews Creek", 7m / 100m);
            state.AddCity("Richfield", 7m / 100m);
            state.AddCity("Spencer", 7m / 100m);
            state.AddCity("Shallotte", 6.75m / 100m);
            state.AddCity("Gold Hill", 7m / 100m);
            state.AddCity("Zirconia", 6.75m / 100m);
            state.AddCity("Hildebran", 6.75m / 100m);
            state.AddCity("Woodleaf", 7m / 100m);
            state.AddCity("Marble", 7m / 100m);
            state.AddCity("Godwin", 7m / 100m);
            state.AddCity("Colerain", 7m / 100m);
            state.AddCity("Garysburg", 6.75m / 100m);
            state.AddCity("Peachland", 7m / 100m);
            state.AddCity("Wagram", 6.75m / 100m);
            state.AddCity("Wrightsville Beach", 7m / 100m);
            state.AddCity("Ronda", 7m / 100m);
            state.AddCity("Oriental", 6.75m / 100m);
            state.AddCity("Star", 7m / 100m);
            state.AddCity("Lumber Bridge", 7m / 100m);
            state.AddCity("Mount Ulla", 7m / 100m);
            state.AddCity("Bethel", 7m / 100m);
            state.AddCity("Conway", 6.75m / 100m);
            state.AddCity("Staley", 7m / 100m);
            state.AddCity("Halifax", 7m / 100m);
            state.AddCity("Cashiers", 7m / 100m);
            state.AddCity("Morven", 7m / 100m);
            state.AddCity("Otto", 6.75m / 100m);
            state.AddCity("Macclesfield", 7m / 100m);
            state.AddCity("Grandy", 6.75m / 100m);
            state.AddCity("Hollister", 7m / 100m);
            state.AddCity("Castalia", 6.75m / 100m);
            state.AddCity("Cove City", 6.75m / 100m);
            state.AddCity("Casar", 6.75m / 100m);
            state.AddCity("Wade", 7m / 100m);
            state.AddCity("Pinebluff", 7m / 100m);
            state.AddCity("Sharpsburg", 6.75m / 100m);
            state.AddCity("Drexel", 6.75m / 100m);
            state.AddCity("Maple Hill", 6.75m / 100m);
            state.AddCity("Hendersonville", 6.75m / 100m);
            state.AddCity("Weldon", 7m / 100m);
            state.AddCity("Lowgap", 7m / 100m);
            state.AddCity("Bath", 6.75m / 100m);
            state.AddCity("Cherry Point", 6.75m / 100m);
            state.AddCity("Moncure", 7m / 100m);
            state.AddCity("Purlear", 7m / 100m);
            state.AddCity("Walstonburg", 7m / 100m);
            state.AddCity("Dover", 6.75m / 100m);
            state.AddCity("Lake Lure", 7m / 100m);
            state.AddCity("Dana", 6.75m / 100m);
            state.AddCity("Currie", 6.75m / 100m);
            state.AddCity("Deep Gap", 6.75m / 100m);
            state.AddCity("Jackson Springs", 7m / 100m);
            state.AddCity("Aurora", 6.75m / 100m);
            state.AddCity("Barnardsville", 7m / 100m);
            state.AddCity("Franklin", 6.75m / 100m);
            state.AddCity("Union Mills", 7m / 100m);
            state.AddCity("Lilesville", 7m / 100m);
            state.AddCity("Elk Park", 6.75m / 100m);
            state.AddCity("Pollocksville", 7m / 100m);
            state.AddCity("Green Mountain", 6.75m / 100m);
            state.AddCity("Olin", 6.75m / 100m);
            state.AddCity("Delco", 6.75m / 100m);
            state.AddCity("Sandy Ridge", 6.75m / 100m);
            state.AddCity("Tyner", 6.75m / 100m);
            state.AddCity("Fleetwood", 7m / 100m);
            state.AddCity("Rosman", 6.75m / 100m);
            state.AddCity("Lake Waccamaw", 6.75m / 100m);
            state.AddCity("Manson", 6.75m / 100m);
            state.AddCity("Rich Square", 6.75m / 100m);
            state.AddCity("Ararat", 7m / 100m);
            state.AddCity("Bolton", 6.75m / 100m);
            state.AddCity("Union Grove", 6.75m / 100m);
            state.AddCity("Boomer", 7m / 100m);
            state.AddCity("Providence", 6.75m / 100m);
            state.AddCity("Hookerton", 7m / 100m);
            state.AddCity("Harrells", 7m / 100m);
            state.AddCity("Cedar Grove", 7.5m / 100m);
            state.AddCity("Turkey", 7m / 100m);
            state.AddCity("Teachey", 7m / 100m);
            state.AddCity("Orrum", 7m / 100m);
            state.AddCity("Chinquapin", 7m / 100m);
            state.AddCity("Zionville", 6.75m / 100m);
            state.AddCity("Creswell", 6.75m / 100m);
            state.AddCity("New Hill", 7.25m / 100m);
            state.AddCity("Knotts Island", 6.75m / 100m);
            state.AddCity("Bunn", 6.75m / 100m);
            state.AddCity("Pantego", 6.75m / 100m);
            state.AddCity("Bayboro", 6.75m / 100m);
            state.AddCity("Pinetown", 6.75m / 100m);
            state.AddCity("Grantsboro", 6.75m / 100m);
            state.AddCity("Sugar Grove", 6.75m / 100m);
            state.AddCity("Albertson", 7m / 100m);
            state.AddCity("Clarendon", 6.75m / 100m);
            state.AddCity("Kure Beach", 7m / 100m);
            state.AddCity("Crumpler", 7m / 100m);
            state.AddCity("Hot Springs", 7m / 100m);
            state.AddCity("Goldston", 7m / 100m);
            state.AddCity("Traphill", 7m / 100m);
            state.AddCity("Cerro Gordo", 6.75m / 100m);
            state.AddCity("Lake Toxaway", 6.75m / 100m);
            state.AddCity("Creston", 7m / 100m);
            state.AddCity("Nakina", 6.75m / 100m);
            state.AddCity("Eagle Springs", 7m / 100m);
            state.AddCity("Tar Heel", 6.75m / 100m);
            state.AddCity("Macon", 6.75m / 100m);
            state.AddCity("Jackson", 6.75m / 100m);
            state.AddCity("Lake Junaluska", 7m / 100m);
            state.AddCity("Wanchese", 6.75m / 100m);
            state.AddCity("Buxton", 6.75m / 100m);
            state.AddCity("Todd", 7m / 100m);
            state.AddCity("Fountain", 7m / 100m);
            state.AddCity("Stella", 7m / 100m);
            state.AddCity("Bullock", 6.75m / 100m);
            state.AddCity("Corapeake", 6.75m / 100m);
            state.AddCity("Danbury", 6.75m / 100m);
            state.AddCity("Penrose", 6.75m / 100m);
            state.AddCity("White Oak", 6.75m / 100m);
            state.AddCity("Bennett", 7m / 100m);
            state.AddCity("Rockingham", 6.75m / 100m);
            state.AddCity("Lewiston Woodville", 7m / 100m);
            state.AddCity("Blounts Creek", 6.75m / 100m);
            state.AddCity("Thurmond", 7m / 100m);
            state.AddCity("Boiling Springs", 6.75m / 100m);
            state.AddCity("Lincolnton", 7m / 100m);
            state.AddCity("Arapahoe", 6.75m / 100m);
            state.AddCity("Glen Alpine", 6.75m / 100m);
            state.AddCity("Sunbury", 6.75m / 100m);
            state.AddCity("Ferguson", 7m / 100m);
            state.AddCity("Lawsonville", 6.75m / 100m);
            state.AddCity("Evergreen", 6.75m / 100m);
            state.AddCity("Semora", 6.75m / 100m);
            state.AddCity("Hallsboro", 6.75m / 100m);
            state.AddCity("Icard", 6.75m / 100m);
            state.AddCity("Leasburg", 6.75m / 100m);
            state.AddCity("Ennice", 6.75m / 100m);
            state.AddCity("Mountain Home", 6.75m / 100m);
            state.AddCity("Fair Bluff", 6.75m / 100m);
            state.AddCity("Eure", 6.75m / 100m);
            state.AddCity("Welcome", 7m / 100m);
            state.AddCity("Gibson", 6.75m / 100m);
            state.AddCity("Badin", 7m / 100m);
            state.AddCity("Atkinson", 6.75m / 100m);
            state.AddCity("Enka", 7m / 100m);
            state.AddCity("Granite Quarry", 7m / 100m);
            state.AddCity("Cooleemee", 6.75m / 100m);
            state.AddCity("Gatesville", 6.75m / 100m);
            state.AddCity("Milton", 6.75m / 100m);
            state.AddCity("Merry Hill", 7m / 100m);
            state.AddCity("Stokes", 7m / 100m);
            state.AddCity("Henrico", 6.75m / 100m);
            state.AddCity("Pine Level", 6.75m / 100m);
            state.AddCity("Faith", 7m / 100m);
            state.AddCity("Harkers Island", 6.75m / 100m);
            state.AddCity("Woodland", 6.75m / 100m);
            state.AddCity("Warrensville", 7m / 100m);
            state.AddCity("Laurel Springs", 6.75m / 100m);
            state.AddCity("Blanch", 6.75m / 100m);
            state.AddCity("Shawboro", 6.75m / 100m);
            state.AddCity("Currituck", 6.75m / 100m);
            state.AddCity("Brasstown", 7m / 100m);
            state.AddCity("Alexis", 7m / 100m);
            state.AddCity("Como", 7m / 100m);
            state.AddCity("Oak City", 7m / 100m);
            state.AddCity("Seaboard", 6.75m / 100m);
            state.AddCity("Terrell", 7m / 100m);
            state.AddCity("Engelhard", 6.75m / 100m);
            state.AddCity("Shiloh", 6.75m / 100m);
            state.AddCity("Rutherford College", 6.75m / 100m);
            state.AddCity("Lexington", 7m / 100m);
            state.AddCity("Tuckasegee", 7m / 100m);
            state.AddCity("Ernul", 6.75m / 100m);
            state.AddCity("Winton", 7m / 100m);
            state.AddCity("Clayton", 6.75m / 100m);
            state.AddCity("Belvidere", 6.75m / 100m);
            state.AddCity("Hobbsville", 6.75m / 100m);
            state.AddCity("Council", 6.75m / 100m);
            state.AddCity("Siloam", 7m / 100m);
            state.AddCity("Powells Point", 6.75m / 100m);
            state.AddCity("Mccutcheon Field", 7m / 100m);
            state.AddCity("Glade Valley", 6.75m / 100m);
            state.AddCity("Bridgeton", 6.75m / 100m);
            state.AddCity("Skyland", 7m / 100m);
            state.AddCity("Ivanhoe", 7m / 100m);
            state.AddCity("Hobgood", 7m / 100m);
            state.AddCity("Marston", 6.75m / 100m);
            state.AddCity("Ocracoke", 6.75m / 100m);
            state.AddCity("Wake Forest", 7.25m / 100m);
            state.AddCity("Prospect Hill", 6.75m / 100m);
            state.AddCity("Edneyville", 6.75m / 100m);
            state.AddCity("Buies Creek", 7m / 100m);
            state.AddCity("Wilmington", 7m / 100m);
            state.AddCity("Dillsboro", 7m / 100m);
            state.AddCity("Fallston", 6.75m / 100m);
            state.AddCity("Manns Harbor", 6.75m / 100m);
            state.AddCity("Black Creek", 6.75m / 100m);
            state.AddCity("Avon", 6.75m / 100m);
            state.AddCity("Warne", 7m / 100m);
            state.AddCity("Sapphire", 7m / 100m);
            state.AddCity("Merritt", 6.75m / 100m);
            state.AddCity("Toast", 7m / 100m);
            state.AddCity("Swanquarter", 6.75m / 100m);
            state.AddCity("East Spencer", 7m / 100m);
            state.AddCity("Mc Grady", 7m / 100m);
            state.AddCity("Mc Adenville", 7m / 100m);
            state.AddCity("Henrietta", 7m / 100m);
            state.AddCity("Linville", 6.75m / 100m);
            state.AddCity("Kelly", 6.75m / 100m);
            state.AddCity("Collettsville", 6.75m / 100m);
            state.AddCity("Jarvisburg", 6.75m / 100m);
            state.AddCity("Dublin", 6.75m / 100m);
            state.AddCity("Cordova", 6.75m / 100m);
            state.AddCity("Corolla", 6.75m / 100m);
            state.AddCity("Webster", 7m / 100m);
            state.AddCity("Topton", 6.75m / 100m);
            state.AddCity("Cofield", 7m / 100m);
            state.AddCity("Olivia", 7m / 100m);
            state.AddCity("Hoffman", 6.75m / 100m);
            state.AddCity("Hatteras", 6.75m / 100m);
            state.AddCity("Rhodhiss", 6.75m / 100m);
            state.AddCity("Ansonville", 7m / 100m);
            state.AddCity("Polkville", 6.75m / 100m);
            state.AddCity("Earl", 6.75m / 100m);
            state.AddCity("Pine Hall", 6.75m / 100m);
            state.AddCity("Harrellsville", 7m / 100m);
            state.AddCity("Frisco", 6.75m / 100m);
            state.AddCity("Micro", 6.75m / 100m);
            state.AddCity("Southmont", 7m / 100m);
            state.AddCity("Kelford", 7m / 100m);
            state.AddCity("Cedar Mountain", 6.75m / 100m);
            state.AddCity("Powellsville", 7m / 100m);
            state.AddCity("Pleasant Hill", 6.75m / 100m);
            state.AddCity("Hamilton", 7m / 100m);
            state.AddCity("Crossnore", 6.75m / 100m);
            state.AddCity("Longwood", 6.75m / 100m);
            state.AddCity("Cliffside", 7m / 100m);
            state.AddCity("Waco", 6.75m / 100m);
            state.AddCity("Pendleton", 6.75m / 100m);
            state.AddCity("Aydlett", 6.75m / 100m);
            state.AddCity("Charlotte", 7.25m / 100m);
            state.AddCity("Caroleen", 7m / 100m);
            state.AddCity("Micaville", 6.75m / 100m);
            state.AddCity("Glenville", 7m / 100m);
            state.AddCity("Harbinger", 6.75m / 100m);
            state.AddCity("Piney Creek", 6.75m / 100m);
            state.AddCity("High Shoals", 7m / 100m);
            state.AddCity("Conetoe", 7m / 100m);
            state.AddCity("Barco", 6.75m / 100m);
            state.AddCity("Patterson", 6.75m / 100m);
            state.AddCity("Lemon Springs", 7m / 100m);
            state.AddCity("Townsville", 6.75m / 100m);
            state.AddCity("Gloucester", 6.75m / 100m);
            state.AddCity("Atlantic", 6.75m / 100m);
            state.AddCity("Fairfield", 6.75m / 100m);
            state.AddCity("Hazelwood", 7m / 100m);
            state.AddCity("Montreat", 7m / 100m);
            state.AddCity("Smyrna", 6.75m / 100m);
            state.AddCity("Coinjock", 6.75m / 100m);
            state.AddCity("Mineral Springs", 6.75m / 100m);
            state.AddCity("Point Harbor", 6.75m / 100m);
            state.AddCity("Grassy Creek", 7m / 100m);
            state.AddCity("Pope Army Airfield", 7m / 100m);
            state.AddCity("Stovall", 6.75m / 100m);
            state.AddCity("Saratoga", 6.75m / 100m);
            state.AddCity("Poplar Branch", 6.75m / 100m);
            state.AddCity("Rodanthe", 6.75m / 100m);
            state.AddCity("Rex", 7m / 100m);
            state.AddCity("Gulf", 7m / 100m);
            state.AddCity("Lynn", 6.75m / 100m);
            state.AddCity("Wise", 6.75m / 100m);
            state.AddCity("Boone", 6.75m / 100m);
            state.AddCity("Davis", 6.75m / 100m);
            state.AddCity("Ether", 7m / 100m);
            state.AddCity("Maple", 6.75m / 100m);
            state.AddCity("Maury", 7m / 100m);
            state.AddCity("Speed", 7m / 100m);
            state.AddCity("Stacy", 6.75m / 100m);
            state.AddCity("Almond", 7m / 100m);
            state.AddCity("Balsam", 7m / 100m);
            state.AddCity("Bonlee", 7m / 100m);
            state.AddCity("Edward", 6.75m / 100m);
            state.AddCity("Falcon", 7m / 100m);
            state.AddCity("Gerton", 6.75m / 100m);
            state.AddCity("Harris", 7m / 100m);
            state.AddCity("Mamers", 7m / 100m);
            state.AddCity("Naples", 6.75m / 100m);
            state.AddCity("Newell", 7.25m / 100m);
            state.AddCity("Norman", 6.75m / 100m);
            state.AddCity("Roduco", 6.75m / 100m);
            state.AddCity("Scotts", 6.75m / 100m);
            state.AddCity("Severn", 6.75m / 100m);
            state.AddCity("Tuxedo", 6.75m / 100m);
            state.AddCity("Calypso", 7m / 100m);
            state.AddCity("Comfort", 7m / 100m);
            state.AddCity("Hassell", 7m / 100m);
            state.AddCity("Kipling", 7m / 100m);
            state.AddCity("Lowland", 6.75m / 100m);
            state.AddCity("Parmele", 7m / 100m);
            state.AddCity("Penland", 6.75m / 100m);
            state.AddCity("Pineola", 6.75m / 100m);
            state.AddCity("Red Oak", 6.75m / 100m);
            state.AddCity("Roxobel", 7m / 100m);
            state.AddCity("Sedalia", 6.75m / 100m);
            state.AddCity("Simpson", 7m / 100m);
            state.AddCity("Tillery", 7m / 100m);
            state.AddCity("Vaughan", 6.75m / 100m);
            state.AddCity("Winfall", 6.75m / 100m);
            state.AddCity("Alamance", 6.75m / 100m);
            state.AddCity("Alliance", 6.75m / 100m);
            state.AddCity("Bat Cave", 6.75m / 100m);
            state.AddCity("Bethania", 7m / 100m);
            state.AddCity("Everetts", 7m / 100m);
            state.AddCity("Falkland", 7m / 100m);
            state.AddCity("Hobucken", 6.75m / 100m);
            state.AddCity("Lakeview", 7m / 100m);
            state.AddCity("Marietta", 7m / 100m);
            state.AddCity("Plumtree", 6.75m / 100m);
            state.AddCity("Potecasi", 6.75m / 100m);
            state.AddCity("Ridgeway", 6.75m / 100m);
            state.AddCity("Scranton", 6.75m / 100m);
            state.AddCity("Sealevel", 6.75m / 100m);
            state.AddCity("Wallburg", 7m / 100m);
            state.AddCity("Altamahaw", 6.75m / 100m);
            state.AddCity("Asheville", 7m / 100m);
            state.AddCity("Brunswick", 6.75m / 100m);
            state.AddCity("Culberson", 7m / 100m);
            state.AddCity("Highfalls", 7m / 100m);
            state.AddCity("Lattimore", 6.75m / 100m);
            state.AddCity("Mc Farlan", 7m / 100m);
            state.AddCity("Montezuma", 6.75m / 100m);
            state.AddCity("Paw Creek", 7.25m / 100m);
            state.AddCity("Saxapahaw", 6.75m / 100m);
            state.AddCity("Stonewall", 6.75m / 100m);
            state.AddCity("Vandemere", 6.75m / 100m);
            state.AddCity("Wentworth", 7m / 100m);
            state.AddCity("Bellarthur", 7m / 100m);
            state.AddCity("Cumberland", 7m / 100m);
            state.AddCity("Middleburg", 6.75m / 100m);
            state.AddCity("Ridgecrest", 7m / 100m);
            state.AddCity("Rural Hall", 7m / 100m);
            state.AddCity("Scottville", 7m / 100m);
            state.AddCity("Cedar Falls", 7m / 100m);
            state.AddCity("Fontana Dam", 7m / 100m);
            state.AddCity("Jonas Ridge", 6.75m / 100m);
            state.AddCity("Minneapolis", 6.75m / 100m);
            state.AddCity("Misenheimer", 7m / 100m);
            state.AddCity("Roaring Gap", 6.75m / 100m);
            state.AddCity("Rocky Mount", 7m / 100m);
            state.AddCity("Salter Path", 6.75m / 100m);
            state.AddCity("Turnersburg", 6.75m / 100m);
            state.AddCity("Balsam Grove", 6.75m / 100m);
            state.AddCity("Cedar Island", 6.75m / 100m);
            state.AddCity("Chimney Rock", 7m / 100m);
            state.AddCity("Marshallberg", 6.75m / 100m);
            state.AddCity("Mount Mourne", 6.75m / 100m);
            state.AddCity("Proctorville", 7m / 100m);
            state.AddCity("Stumpy Point", 6.75m / 100m);
            state.AddCity("Swepsonville", 6.75m / 100m);
            state.AddCity("Valle Crucis", 6.75m / 100m);
            state.AddCity("Wilsons Mills", 6.75m / 100m);
            state.AddCity("Barium Springs", 6.75m / 100m);
            state.AddCity("Linville Falls", 6.75m / 100m);
            state.AddCity("Scaly Mountain", 6.75m / 100m);
            state.AddCity("Margarettsville", 6.75m / 100m);
            state.AddCity("Glendale Springs", 7m / 100m);
            state.AddCity("North Wilkesboro", 7m / 100m);
            state.AddCity("Little Switzerland", 6.75m / 100m);

            var saved = context.SaveChanges();
        }

    }
}
